ALTER TABLE "healthcare_providers"
ADD COLUMN "display_name" TEXT,
ADD COLUMN "document" TEXT,
ADD COLUMN "birth_date" TIMESTAMP(3),
ADD COLUMN "gender" TEXT,
ADD COLUMN "languages" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "professional_category" TEXT,
ADD COLUMN "license_council" TEXT,
ADD COLUMN "license_state" TEXT,
ADD COLUMN "license_document_key" TEXT,
ADD COLUMN "license_document_file_name" TEXT,
ADD COLUMN "license_document_mime_type" TEXT,
ADD COLUMN "license_document_size" INTEGER,
ADD COLUMN "license_document_sha256" TEXT,
ADD COLUMN "license_document_uploaded_at" TIMESTAMP(3),
ADD COLUMN "verification_status" TEXT NOT NULL DEFAULT 'PENDING',
ADD COLUMN "verified_at" TIMESTAMP(3),
ADD COLUMN "approach" TEXT,
ADD COLUMN "education" TEXT,
ADD COLUMN "certifications" TEXT,
ADD COLUMN "years_of_experience" INTEGER,
ADD COLUMN "target_audiences" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "service_modalities" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "clinic_address" TEXT,
ADD COLUMN "home_care_radius_km" INTEGER,
ADD COLUMN "accepted_insurance" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "payment_methods" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "cancellation_policy" TEXT,
ADD COLUMN "clinic_photos" TEXT[] DEFAULT ARRAY[]::TEXT[];
