import type {
	customer_medical_record,
	patient_profile,
	user,
	UserRole,
} from "../../../prisma/generated/prisma/client";

type Override<T> = Partial<T>;

export function makeUser(overrides: Override<user> = {}): user {
	return {
		id: "user-1",
		name: "Test User",
		firstName: "Test",
		lastName: "User",
		phone: null,
		email: "user@example.com",
		emailVerified: false,
		image: null,
		role: "CUSTOMER" as UserRole,
		onboardingCompleted: true,
		onboardingStep: "COMPLETED",
		cpf: null,
		dateOfBirth: null,
		displayName: null,
		document: null,
		birthDate: null,
		gender: null,
		languages: [],
		specialty: null,
		professionalCategory: null,
		professionalId: null,
		professionalCouncilId: null,
		licenseState: null,
		licenseDocumentKey: null,
		licenseDocumentFileName: null,
		licenseDocumentMimeType: null,
		licenseDocumentSize: null,
		licenseDocumentSha256: null,
		licenseDocumentUploadedAt: null,
		verificationStatus: "PENDING",
		verificationRejectionReason: null,
		verifiedAt: null,
		verifiedByUserId: null,
		bio: null,
		approach: null,
		education: null,
		certifications: null,
		yearsOfExperience: null,
		targetAudiences: [],
		serviceModalities: [],
		homeCareRadiusKm: null,
		acceptedInsurance: [],
		paymentMethods: [],
		bookingAvailabilityDays: 90,
		appointmentConfirmationReminderHoursBefore: 24,
		appointmentReminderHoursBefore: 1,
		birthdayGreetingEmailSubjectTemplate: null,
		birthdayGreetingEmailHtmlTemplate: null,
		cancellationPolicy: null,
		cancellationPolicyEnabled: false,
		cancellationPolicyHoursBefore: null,
		cancellationPolicyPenaltyType: null,
		cancellationPolicyFixedFeeCents: null,
		cancellationPolicyPercentage: null,
		cancellationPolicyRequiresJustification: false,
		clinicPhotos: [],
		birthdayGreetingEmailEnabled: false,
		termsAcceptedAt: null,
		lgpdConsentAt: null,
		professionalResponsibilityAcceptedAt: null,
		createdAt: new Date(),
		updatedAt: new Date(),
		...overrides,
	};
}

export function makePatientProfile(
	overrides: Override<patient_profile> = {},
): patient_profile {
	return {
		id: "patient-profile-1",
		fullName: "Patient Profile",
		dateOfBirth: null,
		cpf: null,
		phone: null,
		email: null,
		address: null,
		gender: null,
		relationshipToCustomer: null,
		notes: null,
		customerOwnerId: null,
		createdByHealthcareProviderId: null,
		bloodType: null,
		medications: null,
		chronicPain: null,
		preExistingConditions: null,
		allergies: null,
		surgeries: null,
		familyHistory: null,
		lifestyleNotes: null,
		emergencyContactName: null,
		emergencyContactPhone: null,
		createdAt: new Date(),
		updatedAt: new Date(),
		...overrides,
	};
}

export function makeMedicalRecord(
	overrides: Override<customer_medical_record> = {},
): customer_medical_record {
	return {
		id: "medical-record-1",
		customerId: "customer-1",
		bloodType: null,
		medications: null,
		chronicPain: null,
		preExistingConditions: null,
		allergies: null,
		surgeries: null,
		familyHistory: null,
		lifestyleNotes: null,
		emergencyContactName: null,
		emergencyContactPhone: null,
		createdAt: new Date(),
		updatedAt: new Date(),
		...overrides,
	};
}
